### ISSUE TITLE
Install with webpack setup

### ISSUE THREAD

**Issue by romarmillan91** [quickemailverification/quickemailverification-node#1]
Hi,

Installing this with webpack setup seems to be missing some dependencies.
ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\request\lib'
 @ ./node_modules/request/lib/har.js 3:9-22
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/http_clien
t/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/client.js
 @ ./node_modules/quickemailverification/lib/index.js
 @ ./src/scripts/script.js
 @ ./src/index.js

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in 'node_modules\forever-agent'
 @ ./node_modules/forever-agent/index.js 6:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/http_clien
t/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/client.js
 @ ./node_modules/quickemailverification/lib/index.js
 @ ./src/scripts/script.js
 @ ./src/index.js

ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in 'node_modules\tough-cookie\lib'
 @ ./node_modules/tough-cookie/lib/cookie.js 32:10-24
 @ ./node_modules/request/lib/cookies.js
 @ ./node_modules/request/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/http_clien
t/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/client.js
 @ ./node_modules/quickemailverification/lib/index.js
 @ ./src/scripts/script.js
 @ ./src/index.js

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in 'node_modules\tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 3:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/http_clien
t/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/client.js
 @ ./node_modules/quickemailverification/lib/index.js
 @ ./src/scripts/script.js
 @ ./src/index.js

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'node_modules\forever-agent'
 @ ./node_modules/forever-agent/index.js 7:10-24
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/http_clien
t/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/client.js
 @ ./node_modules/quickemailverification/lib/index.js
 @ ./src/scripts/script.js
 @ ./src/index.js

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in 'node_modules\tunnel-agent'
 @ ./node_modules/tunnel-agent/index.js 4:10-24
 @ ./node_modules/request/lib/tunnel.js
 @ ./node_modules/request/request.js
 @ ./node_modules/request/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/http_clien
t/index.js
 @ ./node_modules/quickemailverification/lib/quick_email_verification/client.js
 @ ./node_modules/quickemailverification/lib/index.js
 @ ./src/scripts/script.js
 @ ./src/index.js

I've tried all of the suggested fix similar to my issues above but none of them worked.
Am I right to assume that this is not compatible with webpack? Or am I just missing something to make this work?

Thanks

**Comment by twa-team** [comment]
Hi,

Could you please make sure that you have set the target value in your webpack config as following?

module.exports = {
  target: 'node'
};
